name: Run included workflows

on: [workflow_dispatch]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - uses: cschleiden/include-workflow@main
      with:
        workflow-steps: ${{ github.workspace }}/.github/workflows/shared/snippet.yml
        
    - uses: cschleiden/include-workflow@main
      with:
        workflow-steps: ${{ github.workspace }}/.github/workflows/shared/snippet2.yml
